---
title: 'Discussion: Critical thinking'
author: "Nikki Fitzherbert"
date: "18 May 2020"
output: html_document
---

### 1. What data was used for comparison?
All 41,183 consecutive admissions of patients from 1 January 2002 to 30 June 2006 who satisfied the SAPS II inclusion criteria from the Dutch National Intensive Care Evaluation's registry of patients admitted to the ICU's of participating hospitals in The Netherlands.

The 86 input variables used corresponded to quantities measured within 24 hours from admission to the ICU and covered demography, physiology, therapy, conditions and organ-system assessments, and comprised of 45 continuous variables, 18 binary and categorical variables, and 23 discrete ordinal variables represented as integers.

### 2. Is the result different from what you expected?
Yes the results are different from what I expected based on what I had read so far about PRIM.

### 3. What criteria were used for comparison?

The authors designed a set of analytical scenarios: The first class were those that the analyst was likely to perform when seeking the *single* best subgroup achievable and the second class were those that the analyst was likely to perform if interested in *all* discoverable subgroups. Thererfore, the authors allowed for iterative discovery of subgroups in PRIM and both iterative and non-iterative discovery in CART. The final class of scenarios was designed to facilitate a "fair" comparison between PRIM and CART by matching their subgroups' support or target mean.

In addition, the authors used two summary measures of relative performance on the independent test set. The first was the coverage ratio, which was defined as:  
$$CR = \frac{C_{PRIM}}{C_{CART}}, \; where \; C = \sum_{k=1}^{K}(\bar y_k - \bar y) \beta_k, \; for \; K \; subgroups$$
The second was the relative adds ratio, which was the ratio between the odds ratio of PRIM to the odds ratio of CART and intuitively describes the strength of the associaton between mortality and membership to a set of subgroups.

### 4. According to the authors, what are the factors that contributed to their findings?


### 5. Can you suggest areas of improvement?

