%creating a function, findSlope, that will find the slope of the line of
%best fit for the random data generated by 'randXY'

function slope = findSlope(x,y)
coeffs = polyfit(x,y,1);
slope = coeffs(1);
end